feat get_irida_sequence_run: get all the sequenceing runs available

diff --git a/get_irida_sequence_run b/get_irida_sequence_run
--- a/get_irida_sequence_run
+++ b/get_irida_sequence_run
@@ -1,11 +1,13 @@
-# get_irida_token_admin
+# get_irida_sequence_run
 # get IRIDA OAuth token for admin account and export as IRIDA_TOKEN
-# reads credentials from Bitwarden via bw serve (must be running on 127.0.0.1:8087)
 #
-# example: get_irida_token_admin && echo "token: ${IRIDA_TOKEN}"
+# examples:
+#   get_irida_sequence_run
+#   get_irida_sequence_run 42
 #
-# WARNING: this exports IRIDA_TOKEN — it will overwrite any existing token.
-# use get_irida_token to revert to the non-admin account.
+# WARNING: this function requires an admin token to get data, 
+# otherwise, you will get an empty json response.
+# use get_irida_token_admin to get the admin account.
 #
 # Copyright (C) 2026 George Marselis <george.marselis@vetinst.no>
 # This program is free software: you can redistribute it and/or modify
@@ -20,7 +22,8 @@
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
-get_irida_token_admin() {
+
+get_irida_sequence_run() {
     if [[ -x /usr/bin/toilet ]]; then
         /usr/bin/toilet -f mono12 --filter border "WARNING" >&2
     fi
@@ -29,8 +32,8 @@ get_irida_token_admin() {
 
 
     if [[ "${_skip_countdown}" -eq 0 ]]; then
-        echo "  You are about to authenticate as the IRIDA admin account." >&2
-        echo "  IRIDA_TOKEN will be overwritten. Use get_irida_token to revert." >&2
+        echo "  You need to have run get_irida_token_admin before running this function." >&2
+        echo "  If you did not, you will get back an emtpy json response." >&2
         echo "  You have 15 seconds to abort:" >&2
         echo "" >&2
         for _i in $(seq 15 -1 1); do
@@ -41,21 +44,17 @@ get_irida_token_admin() {
         echo "" >&2
     fi
 
-    check_bitwarden_serve || { /usr/bin/printf "bw-serve.service not running; start it via\n\tsystemctl --user stop bw-serve.service\n\tsystemctl --user start bw-serve.service\n\t/usr/local/bin/vault_unlock.sh\n" ; return 1 ; }
-    # DO NOT ADD A CHECK FOR THE TOKEN HERE. WE ARE GENERATING THE TOKEN NOW.
     check_irida_connectivity || return 1
+    check_irida_token        || return 1
+    local response
+    response=$( curl --silent -X GET "http://irida.vigasp.vetinst.no:8080/irida-23.01.3/api/sequencingrun/" -H "Authorization: Bearer ${IRIDA_TOKEN}" -H "Accept: application/json" )
+    #response=$( curl --silent -X GET "http://irida.vigasp.vetinst.no:8080/irida-23.01.3/api/sequencingrun/${1%%:*}" -H "Authorization: Bearer ${IRIDA_TOKEN}" -H "Accept: application/json" )
+    [[ -z "${response}" ]] && { echo "project ${1%%:*} not found" ; return 1 ; }
+    [[ $( echo "${response}" | /usr/bin/jq '.resource.resources | length' ) -eq 0 ]] && { echo "project ${1%%:*} has no samples" ; return 1 ; }
+    echo "${response}" | /usr/bin/jq '[.resource.resources[] | {id: .identifier, label: .label, description: .description, sequencerType: .sequencerType, uploadStatus: .uploadStatus, layoutType: .layoutType, created: (.createdDate / 1000 | strftime("%Y-%m-%d")), modified: (.modifiedDate / 1000 | strftime("%Y-%m-%d")), workflow: .workflow}]'  | /usr/bin/mlr --ijson --opprint cat
 
-    export IRIDA_TOKEN=null
-    local BW_URL="http://127.0.0.1:8087"
-    local BW_ITEM="fab1520e-3188-47d3-b1d0-b42400d6ade0"
-    local BW_DATA=$( /usr/bin/curl --silent "${BW_URL}/object/item/${BW_ITEM}" )
-    local USERNAME=$(      echo "${BW_DATA}" | /usr/bin/jq -r '.data.login.username' )
-    local PASSWORD=$(      /usr/bin/urlencode $( echo "${BW_DATA}" | /usr/bin/jq -r '.data.login.password' ) )
-    local CLIENT_ID=$(     echo "${BW_DATA}" | /usr/bin/jq -r '.data.notes' | grep '^client_id:' | /usr/bin/sed 's/^client_id://' )
-    local CLIENT_SECRET=$( echo "${BW_DATA}" | /usr/bin/jq -r '.data.notes' | grep '^token:'     | /usr/bin/sed 's/^token://'     )
-    export IRIDA_TOKEN=$(  /usr/bin/curl --silent -X POST 'http://irida.vigasp.vetinst.no:8080/irida-23.01.3/api/oauth/token' -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&grant_type=password&username=${USERNAME}&password=${PASSWORD}" | /usr/bin/jq -r '.access_token' )
 }
 
-# no tab completion - function takes no arguments
-complete get_irida_token_admin
+# tab complete the sequncing run .identifier:.label
+complete _irida_sequence_run get_irida_sequence_run
 
