fix for get_irida_token_admin: added a --skip-countdown switch

diff --git a/get_irida_token_admin b/get_irida_token_admin
--- a/get_irida_token_admin
+++ b/get_irida_token_admin
@@ -21,24 +21,29 @@
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 get_irida_token_admin() {
-   if [[ -x /usr/bin/toilet ]]; then
+    if [[ -x /usr/bin/toilet ]]; then
         /usr/bin/toilet -f mono12 --filter border "WARNING" >&2
     fi
-    echo "  You are about to authenticate as the IRIDA admin account." >&2
-    echo "  IRIDA_TOKEN will be overwritten. Use get_irida_token to revert." >&2
-    echo "  You have 15 seconds to abort:" >&2
-    echo "" >&2
+    local _skip_countdown=0
+    [[ "${1}" == "--skip-countdown" ]] && _skip_countdown=1
+
+
+    if [[ "${_skip_countdown}" -eq 0 ]]; then
+        echo "  You are about to authenticate as the IRIDA admin account." >&2
+        echo "  IRIDA_TOKEN will be overwritten. Use get_irida_token to revert." >&2
+        echo "  You have 15 seconds to abort:" >&2
+        echo "" >&2
+        for _i in $(seq 15 -1 1); do
+            printf "\r  %2d ... " "${_i}" >&2
+            sleep 1
+        done
+        printf "\r         \r" >&2
+        echo "" >&2
+    fi
 
     check_bitwarden_serve || { /usr/bin/printf "bw-serve.service not running; start it via\n\tsystemctl --user stop bw-serve.service\n\tsystemctl --user start bw-serve.service\n\t/usr/local/bin/vault_unlock.sh\n" ; return 1 ; }
     # DO NOT ADD A CHECK FOR THE TOKEN HERE. WE ARE GENERATING THE TOKEN NOW.
     check_irida_connectivity || return 1
-
-     for _i in $(seq 15 -1 1); do
-        printf "\r  %2d ... " "${_i}" >&2
-        sleep 1
-    done
-    printf "\r         \r" >&2
-    echo "" >&2
 
     local BW_URL="http://127.0.0.1:8087"
     local BW_ITEM="fab1520e-3188-47d3-b1d0-b42400d6ade0"
